config/routes.rb
Rails.application.routes.draw do
  resources :news do
    patch "approve", on: :member
  end
  resources :politicians do
    post :news, on: :member
  end
  resources :political_parties do
    post :news, on: :member
  end
  resources :users
  root 'static_pages#home'
  get '/politicos', to: 'politicians#index'
  get '/partidos', to: 'political_parties#index'
  get '/noticias', to: 'news#index'
  get '/modpartidos', to: 'political_parties#mod'
  get '/modpoliticos', to: 'politicians#mod'
  get '/modnoticias', to: 'news#mod'
  get '/historial', to: 'news#record'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/political_party.rb
class PoliticalParty < ApplicationRecord
  self.per_page = 2
  has_one_attached :picture
  has_many :news, as: :origin
  has_many :politicians, :dependent => :delete_all
end

app/controllers/political_parties_controller.rb
class PoliticalPartiesController < ApplicationController
  before_action :set_political_party, only: [:show, :edit, :update, :destroy]

  # GET /political_parties
  # GET /political_parties.json
  def index
    @political_parties = PoliticalParty.all
  end
  
  # GET /political_parties/mod
  # GET /political_parties.json
  def mod
    if params[:search]
      @political_parties = PoliticalParty.where("name LIKE :search OR coalition LIKE :search", search: "%#{params[:search]}%").paginate(page: params[:page], per_page: 10)
    else
      @political_parties = PoliticalParty.all.paginate(page: params[:page], per_page: 10)
    end
  end

  # GET /political_parties/1
  # GET /political_parties/1.json
  def show
    @party = PoliticalParty.find(params[:id])
    @news = @party.news.order(params[:release]).paginate(page: params[:page], per_page: 5)
    @politicians = @party.politicians.order(params[:birthdate]).paginate(page: params[:page], per_page: 5)
    @suggestion = News.new
  end

  # GET /political_parties/new
  def new
    @political_party = PoliticalParty.new
  end

  # GET /political_parties/1/edit
  def edit
  end

  # POST /political_parties
  # POST /political_parties.json
  def create
    @political_party = PoliticalParty.new(political_party_params)

    respond_to do |format|
      if @political_party.save
        format.html { redirect_to @political_party, notice: 'Political party was successfully created.' }
        format.json { render :show, status: :created, location: @political_party }
      else
        format.html { render :new }
        format.json { render json: @political_party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /political_parties/1
  # PATCH/PUT /political_parties/1.json
  def update
    respond_to do |format|
      if @political_party.update(political_party_params)
        format.html { redirect_to '/modpartidos', notice: 'Political party was successfully updated.' }
        format.json { render :show, status: :ok, location: @political_party }
      else
        format.html { render :edit }
        format.json { render json: @political_party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /political_parties/1
  # DELETE /political_parties/1.json
  def destroy
    @political_party.destroy
    respond_to do |format|
      format.html { redirect_to '/modpartidos', notice: 'Political party was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_political_party
      @political_party = PoliticalParty.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def political_party_params
      params.require(:political_party).permit(:name, :founding, :political_compass, :coalition, :founding_ideology, :principles, :picture)
    end
end

app/helpers/political_parties_helper.rb
module PoliticalPartiesHelper
end

app/views/political_parties/_form.html.erb
<%= form_with(model: political_party) do |form| %>
  <% if political_party.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(political_party.errors.count, "error") %> prohibited this political_party from being saved:</h2>

      <ul>
        <% political_party.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :founding %>
    <%= form.date_select :founding %>
  </div>

  <div class="field">
    <%= form.label :political_compass %>
    <%= form.text_field :political_compass %>
  </div>

  <div class="field">
    <%= form.label :coalition %>
    <%= form.text_field :coalition %>
  </div>

  <div class="field">
    <%= form.label :founding_ideology %>
    <%= form.text_field :founding_ideology %>
  </div>

  <div class="field">
    <%= form.label :principles %>
    <%= form.text_field :principles %>
  </div>
  
  <div>
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/political_parties/edit.html.erb
<h1>Editing Political Party</h1>

<%= render 'form', political_party: @political_party %>

<%= link_to 'Show', @political_party %> |
<%= link_to 'Back', '/modpartidos' %>

app/views/political_parties/index.html.erb
<p id="notice"><%= notice %></p>
<center>
<h1>Partidos</h1>
</center>
<div class="row row-cols-1 row-cols-lg-2 g-3 mb-2 mt-3">
        <% @political_parties.each do |political_party| %>
          <div class="col">
            <div class="card news-card overflow-hidden">
              <a class="row g-0 h-100" href="/political_parties/<%= political_party.id %>" target="_blank">
                <div class="col-4">
                  <%= image_tag(political_party.picture, class: "h-100 w-100 rounded-start") %>
                </div>
                <div class="col-8">
                  <div class="card-body h-100">
                    <h5><%= political_party.name %></h5>
                    <ul class="py-2 px-3 list-unstyled politician-details-list mb-0">
                      <li>
                        <i class="bi bi-compass me-2 fs-6 pt-1"></i>
                        <p>
                          <%=  political_party.political_compass%>
                        </p>
                      </li>
                      <li>
                        <p>
                          <i class="bi bi-gear-wide me-2 fs-6 "></i>
                          <%= political_party.coalition %>
                        </p>
                      </li>
                      <li>
                        <i class="bi bi-clock-history me-2 fs-6 pe-1"></i> 
                        <p>
                          <%=  political_party.founding%>
                        </p>
                      </li>
                    </ul>
                  </div>
                </div>
              </a>
            </div>
          </div>
        <% end %>
<!--<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Founding</th>
      <th>Political compass</th>
      <th>Coalition</th>
      <th>Founding ideology</th>
      <th>Principles</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @political_parties.each do |political_party| %>
      <tr>
        <td><%= political_party.name %></td>
        <td><%= political_party.founding %></td>
        <td><%= political_party.political_compass %></td>
        <td><%= political_party.coalition %></td>
        <td><%= political_party.founding_ideology %></td>
        <td><%= political_party.principles %></td>
        <td><%= link_to 'Show', political_party %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>-->

app/views/political_parties/mod.html.erb
<h1>Political Parties</h1>
  <% if logged_in? %>
      <%= form_tag('modpartidos', method: :get) do %>
        <%= text_field_tag(:search, params[:search]) %>
        <%= submit_tag ("Search") %>
      <% end %>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Founding</th>
          <th>Political compass</th>
          <th>Coalition</th>
          <th>Founding ideology</th>
          <th>Principles</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @political_parties.each do |political_party| %>
          <tr>
            <td><%= political_party.name %></td>
            <td><%= political_party.founding %></td>
            <td><%= political_party.political_compass %></td>
            <td><%= political_party.coalition %></td>
            <td><%= political_party.founding_ideology %></td>
            <td><%= political_party.principles %></td>
            <td><%= link_to 'Show', political_party %></td>
            <td><%= link_to 'Edit', edit_political_party_path(political_party) %></td>
            <td><%= link_to 'Destroy', political_party, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
        <div class="digg_pagination  mt-3 ">
          <%= will_paginate @parties %>
        </div>
    
    <br>
    
    <%= link_to 'New Political Party', new_political_party_path %>
  <% else %>
    <% controller.redirect_to root_path %>
  <% end %>

app/views/political_parties/new.html.erb
<h1>New Political Party</h1>

<%= render 'form', political_party: @political_party %>

<%= link_to 'Back', '/modpartidos' %>

app/views/political_parties/show.html.erb
<div class="container">
  <div class="row mb-4">
    <div class="col px-0">
      <div class="card party-info-card bg-white">
        <div class="row g-0 flex-nowrap h-100">
          <div class="col flex-fill">
            <div class="card-body p-4">
              <h1 class="card-title mb-3"><strong><%= @political_party.name %></strong></h1>
              <% if @politicians.empty? %>
                <p class="card-text fs-5 lh-sm">
                  El partido "<%= @political_party.name %>" de la <%= @political_party.political_compass %> fue fundado el <%= @political_party.founding %>,
                  bajo las ideologias del <%= @political_party.founding_ideology %>.
                  y pertenece a la coalicion <%= @political_party.coalition %>
                </p>
              <% else %>
                <p class="card-text fs-5 lh-sm">
                  El partido "<%= @political_party.name %>" de la <%= @political_party.political_compass %> fue fundado el <%= @political_party.founding %>,
                  bajo las ideologias del <%= @political_party.founding_ideology %>.
                  Actualmente liderado por <%= @politicians.first.name %>,
                  y pertenece a la coalicion <%= @political_party.coalition %>
                </p>
              <% end %>
              <a class="card-text "><p class="text-end fs-6">Declaracion de principios</p></a>
              
            </div>
          </div>
          <div class="col h-100">
            <%= image_tag(@political_party.picture, class: "h-100 w-auto rounded-end political-party-logo") %>
<!--            <img src="https://via.placeholder.com/300x250" class="h-100 w-auto rounded-end political-party-logo" />-->          
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-3 rounded">
        <h4 class="fw-bold mb-4 pt-3 text-center"><strong>Miembros</strong></h4>
          <div class="row row-cols-1 g-3">
            <%= render 'layouts/politicians' %>
          </div>
    </div>
    <div class="col-8 offset-1 bg-white rounded px-4 pt-2">
      <h4 class="fw-bold mb-4 pt-3"><strong>Ultimas noticias</strong></h4>
      <div class="row row-cols-1 g-3">
        <%= render 'layouts/news' %>
      </div>
    </div>
    <%= render 'news/form', news: @suggestion, suggestion_to_name: @political_party.name, suggestion_to_id: @political_party.id, suggestion_to_type: @political_party.class %>
</div>


<!--<p>-->
<!--  <strong>Name:</strong>-->
<!--  <%= @political_party.name %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Founding:</strong>-->
<!--  <%= @political_party.founding %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Political compass:</strong>-->
<!--  <%= @political_party.political_compass %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Coalition:</strong>-->
<!--  <%= @political_party.coalition %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Founding ideology:</strong>-->
<!--  <%= @political_party.founding_ideology %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Principles:</strong>-->
<!--  <%= @political_party.principles %>-->
<!--</p>-->


<!--<%= link_to 'Edit', edit_political_party_path(@political_party) %> |-->
<!--<%= link_to 'Back', political_parties_path %>-->
<!--<p id="notice"><%= notice %></p>-->