config/routes.rb
Rails.application.routes.draw do
  resources :news do
    patch "approve", on: :member
  end
  resources :politicians do
    post :news, on: :member
  end
  resources :political_parties do
    post :news, on: :member
  end
  resources :users
  root 'static_pages#home'
  get '/politicos', to: 'politicians#index'
  get '/partidos', to: 'political_parties#index'
  get '/noticias', to: 'news#index'
  get '/modpartidos', to: 'political_parties#mod'
  get '/modpoliticos', to: 'politicians#mod'
  get '/modnoticias', to: 'news#mod'
  get '/historial', to: 'news#record'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/news.rb
class News < ApplicationRecord
  self.per_page = 4
  belongs_to :origin, polymorphic: true
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy, :approve]

  # GET /news
  # GET /news.json
  def index
    @news = News.order(params[:release]).paginate(page: params[:page], per_page: 16)
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end
  
  def mod 
    @news = News.where(state: false).order(params[date: :asc]).paginate(page: params[:page], per_page: 8)
  end
  
  def record
      @news = News.where(state: true).order(params[date: :asc]).paginate(page: params[:page], per_page: 8)
  end
  
  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news.origin, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news.origin }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to '/modnoticias', notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def approve
    @news.update(state: true)
    respond_to do |format|
      format.html { redirect_to '/modnoticias', notice: 'News was successfully updated.' }
      format.json { head :no_content }
    end
  end  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:title, :link, :release, :email, :origin_id, :origin_type, :state)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_with(model: news) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
        <% news.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row bg-white rounded px-2 py-4 my-4">
    <h5 class="mb-4">Agrega una noticia sobre <%= suggestion_to_name %> </h5>
    <div class="col">
      <%= form.text_field :title, class: "form-control mb-3", placeholder: "Titulo", required: true %>
      <%= form.text_field :link, class: "form-control", placeholder: "Enlace", required: true %>
    </div>
    <div class="col d-flex flex-column ">
      <%= form.email_field :email, class: "form-control mb-3", placeholder: "Correo", required: true %>
      <div class="d-flex flex-row">
        <span class="me-2 flex-grow-1"><strong>Fecha Noticia:</strong></span>
        <%= form.date_select :release, :with_css_classes => {:year => "form-select-sm me-2 ", :month => "form-select-sm me-2 w-50", :day => "form-select-sm" }, :use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre'] %>
      </div>
      <%= form.hidden_field :origin_id, :value => suggestion_to_id %>
      <%= form.hidden_field :origin_type, :value => suggestion_to_type %>
      <%= form.submit 'Sugerir', :class => 'mt-4 w-25 btn btn-primary align-self-end' %>
    </div>
  </div>

  <!--<div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="field">
    <%= form.label :release %>
    <%= form.date_select :release %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.hidden_field :origin_id, :value => @id %>
    <%= form.hidden_field :origin_type, :value => @type %>
  </div>
  
  <div class="field">
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>-->
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<p id="notice"><%= notice %></p>

<center>
  <h1>Noticias</h1>
</center>
<div class="row row-cols-1 row-cols-lg-2 g-3 mt-2">
  <% @news.each do |news| %>
    <div class="col">
      <div class="card news-card overflow-hidden">
        <a class="row g-0 h-100" href="<%= news.link %>" target="_blank">
          <div class="col-4">
            <img src="https://via.placeholder.com/400x300" class="h-100 w-100 rounded-start" />
          </div>
          <div class="col-8">
            <div class="card-body h-100">
              <h5><%= news.title %></h5>
              <p class="card-text"><small class="text-primary"><%= news.release %></small></p>
            </div>
          </div>
        </a>
      </div>
    </div>
  <% end %>
  <div class="digg_pagination  mt-3 ">
    <%= will_paginate @news %>
  </div>
</div>

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Title</th>-->
<!--      <th>Link</th>-->
<!--      <th>Release</th>-->
<!--      <th>Email</th>-->
<!--      <th>Origin</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--    <% @news.each do |news| %>-->
<!--      <tr>-->
<!--        <td><%= news.title %></td>-->
<!--        <td><%= news.link %></td>-->
<!--        <td><%= news.release %></td>-->
<!--        <td><%= news.email %></td>-->
<!--        <td><%= news.origin_id %></td>-->
<!--        <td><%= link_to 'Show', news %></td>-->
<!--        <td><%= link_to 'Edit', edit_news_path(news) %></td>-->
<!--        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
<!--    <% end %>-->
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->

<!--<%= link_to 'New News', new_news_path %>-->

app/views/news/mod.html.erb
<center>
  <h1 class="mt-3">Sugerencias</h1>
  <div class="row row-cols-1 g-3 mt-2 max-width-900 align-self-center">
    <div class="btn-group my-3">
      <a href="#" class="btn btn-primary active" aria-current="page">Pendientes</a>
      <a href="/historial" class="btn btn-primary">Historial</a>
    </div>
    <% @news.each do |news| %>
      <div class="col">
        <div class="card news-card overflow-hidden ">
          <div class="row g-0 h-100">
            <div class="col-4 h-100">
              <img src="https://via.placeholder.com/400x300" class="h-100 w-100 rounded-start">
            </div>
            <div class="col-6">
              <div class="card-body h-100 text-start">
                <h5><%= news.title %></h5>
                <%= link_to news.link, news.link, class: "mb-2" %>
                <p class="mb-2"><%= news.origin.name %></p>
                <p class="mb-2"><%= news.release %></p>
                <!--<p class="mb-2"><%= news.link %></p>-->
                <!--<p class="card-text"><small class="text-primary"><%= news.release %></small></p>-->
              </div>
            </div>
            <div class="col-2">
              <div class="btn-group-vertical h-100 w-100" role="group">
                <!--<%= link_to 'Aprobar', news %>-->
                <%= link_to approve_news_path(news) , method: :patch, class: "btn btn-success d-flex align-items-center justify-content-center" do %>
                  <span>Aprobar</span>
                <% end %>
                <%= link_to news, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger d-flex align-items-center justify-content-center" do %>
                  <span>Eliminar</span>
                <% end %>
                <!--<%= link_to news, method: :get, class: "btn btn-secondary d-flex align-items-center justify-content-center" do %>
                  <span>Editar</span>
                <% end %>-->
                <!--<button type="button" class="btn btn-success" >Aprobar</button>-->
                <!--<button type="button" class="btn btn-danger">Eliminar</button>
                <button type="button" class="btn btn-secondary">Editar</button>-->
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="digg_pagination  mt-3 ">
      <%= will_paginate @news %>
    </div>
  </div>
</center>


<!--<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th>Release</th>
      <th>Email</th>
      <th>Origin</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.where(state: false).each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.link %></td>
        <td><%= news.release %></td>
        <td><%= news.email %></td>
        <td><%= news.origin.name %></td>
        <td><%= news.state %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News', new_news_path %>-->

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', '/modnoticias' %>

app/views/news/record.html.erb
<% if logged_in? %>
<center>
  <h1 class="mt-3">Historial</h1>
  <div class="row row-cols-1 g-3 mt-2 max-width-900 align-self-center">
    <div class="btn-group my-3">
      <a href="/modnoticias" class="btn btn-primary" aria-current="page">Pendientes</a>
      <a href="#" class="btn btn-primary active">Historial</a>
    </div>
    <!--<%= form_tag('historial', method: :get) do %>
      <%= text_field_tag(:search, params[:search], placeholder: "Titulo", class:"form-control w-75 mx-0") %>
      <%= submit_tag ("Search"), class:"btn btn-primary mb-3" %>
    <% end %>-->
    <% @news.each do |news| %>
      <div class="col">
        <div class="card news-card overflow-hidden ">
          <div class="row g-0 h-100">
            <div class="col-4 h-100">
              <img src="https://via.placeholder.com/400x300" class="h-100 w-100 rounded-start">
            </div>
            <div class="col-6">
              <div class="card-body h-100 text-start">
                <h5><%= news.title %></h5>
                <p class="mb-2"><%= news.link %></p>
                <p class="mb-2"><%= news.origin.name %></p>
                <p class="mb-2"><%= news.release %></p>
                <!--<p class="card-text"><small class="text-primary"><%= news.release %></small></p>-->
              </div>
            </div>
            <div class="col-2">
              <div class="btn-group-vertical h-100 w-100" role="group">
                <%= link_to news.link, class: "btn btn-secondary d-flex align-items-center justify-content-center" do %>
                  <span>Ingresar</span>
                <% end %>
                <%= link_to news, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger d-flex align-items-center justify-content-center" do %>
                  <span>Eliminar</span>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="digg_pagination  mt-3 ">
      <%= will_paginate @news %>
    </div>
  </div>
</center>
<% else %>
    <% controller.redirect_to root_path %>
<% end %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Link:</strong>
  <%= @news.link %>
</p>

<p>
  <strong>Release:</strong>
  <%= @news.release %>
</p>

<p>
  <strong>Email:</strong>
  <%= @news.email %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @news.origin_id %>
</p>

<!--<%= link_to 'Edit', edit_news_path(@news) %>--> |
<%= link_to 'Back', '/modnoticias' %>