config/routes.rb
Rails.application.routes.draw do
  resources :news do
    patch "approve", on: :member
  end
  resources :politicians do
    post :news, on: :member
  end
  resources :political_parties do
    post :news, on: :member
  end
  resources :users
  root 'static_pages#home'
  get '/politicos', to: 'politicians#index'
  get '/partidos', to: 'political_parties#index'
  get '/noticias', to: 'news#index'
  get '/modpartidos', to: 'political_parties#mod'
  get '/modpoliticos', to: 'politicians#mod'
  get '/modnoticias', to: 'news#mod'
  get '/historial', to: 'news#record'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/politician.rb
class Politician < ApplicationRecord
  has_one_attached :picture
  belongs_to :political_party
  has_many :news, as: :origin
end

app/controllers/politicians_controller.rb
class PoliticiansController < ApplicationController
  before_action :set_politician, only: [:show, :edit, :update, :destroy]

  # GET /politicians
  # GET /politicians.json
  def index
    @parties = PoliticalParty.all.paginate(page: params[:page], per_page: 2)
    @politicians = Politician.all
  end
  
  def mod
    if params[:search]
      @politicians = Politician.where("name LIKE :search", search: "%#{params[:search]}%").paginate(page: params[:page], per_page: 10)
    else
      @politicians = Politician.all.paginate(page: params[:page], per_page: 10)
    end
  end

  # GET /politicians/1
  # GET /politicians/1.json
  def show
    @politician = Politician.find(params[:id])
    @news = @politician.news.order(params[:release]).paginate(page: params[:page])
    @suggestion = News.new
  end

  # GET /politicians/new
  def new
    @parties = PoliticalParty.order(:name).to_a
    @politician = Politician.new
  end

  # GET /politicians/1/edit
  def edit
  end

  # POST /politicians
  # POST /politicians.json
  def create
    @politician = Politician.new(politician_params)

    respond_to do |format|
      if @politician.save
        format.html { redirect_to '/modpoliticos', notice: 'Politician was successfully created.' }
        format.json { render :show, status: :created, location: @politician }
      else
        format.html { render :new }
        format.json { render json: @politician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /politicians/1
  # PATCH/PUT /politicians/1.json
  def update
    respond_to do |format|
      if @politician.update(politician_params)
        format.html { redirect_to '/modpoliticos', notice: 'Politician was successfully updated.' }
        format.json { render :show, status: :ok, location: @politician }
      else
        format.html { render :edit }
        format.json { render json: @politician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /politicians/1
  # DELETE /politicians/1.json
  def destroy
    @politician.destroy
    respond_to do |format|
      format.html { redirect_to '/modpoliticos', notice: 'Politician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_politician
      @politician = Politician.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def politician_params
      params.require(:politician).permit(:name, :birthdate, :position, :political_compass, :previous_position, :education, :president, :political_party_id, :picture)
    end
end

app/helpers/politicians_helper.rb
module PoliticiansHelper
end

app/views/politicians/_form.html.erb
<%= form_with(model: politician) do |form| %>
  <% if politician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(politician.errors.count, "error") %> prohibited this politician from being saved:</h2>

      <ul>
        <% politician.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.date_select :birthdate %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div>

  <div class="field">
    <%= form.label :political_compass %>
    <%= form.text_field :political_compass %>
  </div>

  <div class="field">
    <%= form.label :previous_position %>
    <%= form.text_field :previous_position %>
  </div>

  <div class="field">
    <%= form.label :education %>
    <%= form.text_field :education %>
  </div>

  <div class="field">
    <%= form.label :president %>
    <%= form.check_box :president %>
  </div>

  <div class="field">
    <%= form.label :political_party_id %>
    <%= form.collection_select :political_party_id, PoliticalParty.order(:name), :id, :name %>
  </div>
  <div>
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>
    

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/politicians/edit.html.erb
<h1>Editing Politician</h1>

<%= render 'form', politician: @politician %>

<%= link_to 'Show', @politician %> |
<%= link_to 'Back', '/modpoliticos' %>

app/views/politicians/index.html.erb
<p id="notice"><%= notice %></p>

<center>
  <h1>Politicos</h1>
</center>
<br/>
  <% @parties.each do |party| %>
    <div class="bg-primary text-white ps-3 pt-3 rounded">
      <h2 > <%= party.name %>s</h2>
      <hr/>
    </div>
      <div class="row row-cols-1 row-cols-lg-2 g-3 mb-2">
        <% @politicians.where(political_party_id: party.id).each do |politician| %>
          <div class="col">
            <div class="card news-card overflow-hidden">
              <a class="row g-0 h-100" href="/politicians/<%= politician.id %>" target="_blank">
                <div class="col-4">
                  <%= image_tag(politician.picture, class: "h-100 w-100 rounded-start") %>
                </div>
                <div class="col-8">
                  <div class="card-body h-100">
                    <h5><%= politician.name %></h5>
                    <ul class="p-3 list-unstyled politician-details-list mb-0">
                      <li>
                        <i class="bi bi-clock-history me-2 fs-6 pe-1"></i> 
                        <p>
                          <%= ((Time.zone.now - politician.birthdate.to_time) / 1.year.seconds).floor  %> años
                        </p>
                      </li>
                      <li>
                        <p>
                          <i class="bi bi-gear-wide me-2 fs-6 "></i>
                          <%= politician.position %>
                        </p>
                      </li>
                    </ul>
                  </div>
                </div>
              </a>
            </div>
          </div>
        <% end %>
      </div>
  <% end %>
  <div class="digg_pagination  mt-3 ">
    <%= will_paginate @parties %>
  </div>
  
<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Name</th>-->
<!--      <th>Birthdate</th>-->
<!--      <th>Position</th>-->
<!--      <th>Political compass</th>-->
<!--      <th>Previous position</th>-->
<!--      <th>Education</th>-->
<!--      <th>President</th>-->
<!--      <th>Political party</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--    <% @politicians.each do |politician| %>-->
<!--      <tr>-->
<!--        <td><%= politician.name %></td>-->
<!--        <td><%= politician.birthdate %></td>-->
<!--        <td><%= politician.position %></td>-->
<!--        <td><%= politician.political_compass %></td>-->
<!--        <td><%= politician.previous_position %></td>-->
<!--        <td><%= politician.education %></td>-->
<!--        <td><%= politician.president %></td>-->
<!--        <td><%= politician.political_party_id %></td>-->
<!--        <td><%= link_to 'Show', politician %></td>-->
<!--        <td><%= link_to 'Edit', edit_politician_path(politician) %></td>-->
<!--        <td><%= link_to 'Destroy', politician, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
<!--    <% end %>-->
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->

<!--<%= link_to 'New Politician', new_politician_path %>-->

app/views/politicians/mod.html.erb
<h1>Politicos</h1>
<% if logged_in? %>
    <%= form_tag('modpoliticos', method: :get) do %>
    <%= text_field_tag(:search, params[:search]) %>
    <%= submit_tag ("Search") %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birthdate</th>
      <th>Position</th>
      <th>Political compass</th>
      <th>Previous position</th>
      <th>Education</th>
      <th>President</th>
      <th>Political party</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @politicians.each do |politician| %>
      <tr>
        <td><%= politician.name %></td>
        <td><%= politician.birthdate %></td>
        <td><%= politician.position %></td>
        <td><%= politician.political_compass %></td>
        <td><%= politician.previous_position %></td>
        <td><%= politician.education %></td>
        <td><%= politician.president %></td>
        <td><%= politician.political_party.name %></td>
        <td><%= link_to 'Show', politician %></td>
        <td><%= link_to 'Edit', edit_politician_path(politician) %></td>
        <td><%= link_to 'Destroy', politician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    <div class="digg_pagination  mt-3 ">
          <%= will_paginate @politicians %>
    </div>

<br>

<%= link_to 'New Politician', new_politician_path %>
<% else %>
    <% controller.redirect_to root_path %>
<% end %>

app/views/politicians/new.html.erb
<h1>New Politician</h1>

<%= render 'form', politician: @politician %>

<%= link_to 'Back', '/modpoliticos' %>

app/views/politicians/show.html.erb
<div class="container pt-4">
  <div class="row">
    <div class="col-3 bg-white rounded p-0 fit-content shadow-sm">
      <div>
        <%= image_tag(@politician.picture, class: "rounded-top img-fluid") %>
      </div>
      <div class="p-0">
        <div class="bg-primary text-white p-3">
          <h4>
            <strong><%= @politician.name %></strong>
          </h4>
          <p class="mb-0">
            <%= @politician.position %>
          </p>
        </div>
        <ul class="p-3 list-unstyled politician-details-list mb-0">
          <li>
            <i class="bi bi-calendar-event me-2 fs-4 pt-1"></i>
            <p>
              <strong>Fecha de nacimiento:</strong>
              <br/>
              <%= @politician.birthdate %>
            </p>
          </li>
          <li>
              
            <i class="bi bi-flag me-2 fs-4 pt-1"></i>
            <p>
              <strong>Partido politico:</strong>
              <br/>
              <%= @politician.political_party.name %>
            </p>
          </li>
          <li>
            <i class="bi bi-compass me-2 fs-4 pt-1"></i>
            <p>
              <strong>Compas politico:</strong>
              <br/>  
              <%= @politician.political_compass %>
            </p>
          </li>
          <li>
            <i class="bi bi-person-lines-fill me-2 fs-4 pt-1"></i>
            <p>
              <strong>Cargos anteriores:</strong>
              <br/>
              <%= @politician.previous_position %>
            </p>
          </li>
          <li>
            <i class="bi bi-award me-2 fs-4 pt-1"></i>
            <p>
              <strong>Educacion:</strong>
              <br/>
              <%= @politician.education %>
            </p>
          </li>
        </ul>
        
      </div>
    </div>
    <div class="col-8 offset-1 rounded p-4">
      <h4 class="fw-bold mb-4"><strong>Ultimas noticias</strong></h4>
      <div class="row row-cols-1 g-3">
        <%= render 'layouts/news' %>
      </div>
    </div>
  </div>
      
      <%= render 'news/form', news: @suggestion, suggestion_to_name: @politician.name, suggestion_to_id: @politician.id, suggestion_to_type: @politician.class %>
</div>
   




<!--<p id="notice"><%= notice %></p>-->

<!--<p>-->
<!--  <strong>Name:</strong>-->
<!--  <%= @politician.name %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Birthdate:</strong>-->
<!--  <%= @politician.birthdate %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Position:</strong>-->
<!--  <%= @politician.position %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Political compass:</strong>-->
<!--  <%= @politician.political_compass %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Previous position:</strong>-->
<!--  <%= @politician.previous_position %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Education:</strong>-->
<!--  <%= @politician.education %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>President:</strong>-->
<!--  <%= @politician.president %>-->
<!--</p>-->

<!--<p>-->
<!--  <strong>Political party:</strong>-->
<!--  <%= @politician.political_party_id %>-->
<!--</p>-->

<!--<%= link_to 'Edit', edit_politician_path(@politician) %> |-->
<!--<%= link_to 'Back', politicians_path %>-->